### ISSUE TITLE
Split clangdev libraries/headers to separate feedstock?

### ISSUE THREAD

**Issue by ezyang** [conda-forge/clangdev-feedstock#15]
Hey all,

I have some applications which MUST link against clang headers from 4.0.0, but I would still like to use the system installation of clang (older) as it is required by nvcc. The current way clangdev's feedstock is setup makes it difficult to do this, as I always get both the libraries/headers as well as the clang binaries as a package deal. Is there some way we can split them up so they are installable separately? (For backwards compatibility, I would assume that clangdev continues to ship both, and there would be a separate libraries only package added.) I'm willing to put in the work if this is something that you would support.

**Comment by jakirkham** [comment]
If you are building a simple C application, there is no need to have `clangdev` as a run time dependency. That said, if you are using C++ or OpenMP, there are some known issues due to `clangdev` being a run time dependency. At least with the C++ case, static linking is a viable workaround/option. Though we are discussing how to resolve dependencies on dynamic libraries for C++ and OpenMP. It may be best resolved once `conda-build` 3 is generally available in `conda-forge`.

Could you please share some more about your use case? For example what features are you using? What is needed at runtime? And so on?

**Comment by ezyang** [comment]
Hi @jakirkham, thanks for responding. So if I understand correctly, the suggestion is to list clangdev as a compile-time dependency ONLY, and make sure that we statically link against clangdev. (Actually, in general, I have always found it a bit murky how to determine the runtime versus compile dependencies of libraries I package.) As PET is not my project, I do not actually know if this will work but it seems like something to try first.

**Comment by jakirkham** [comment]
@isuruf, this has already happened right or are there things that still need to be done here?

**Comment by isuruf** [comment]
Yes
